### ISSUE TITLE
doesn't count the days

### ISSUE THREAD

**Issue by k0st1an** [dontshoot11/serbian_days#3]
![image](https://github.com/user-attachments/assets/ac2aabcc-5927-4680-a7ea-9443f4b1d386)

Hi! As I understand it, after the code update on November 2, it stopped working :)

**Comment by dontshoot11** [comment]
Hey! Thanks for telling me. 
I made a mistake and forgot to include [astro-relative-links](https://www.npmjs.com/package/astro-relative-links) in the updated version, it is necessary for the correct paths to assets in production build.
Fixed it, it should work now

**Comment by k0st1an** [comment]
I confirm, it's working now. Thx!)
